# GET /
index:
    type: rest
    resource: "N3rtrivium\KakonuntiumBundle\Controller\IndexController"

# POST /users
users:
    type: rest
    resource: "N3rtrivium\KakonuntiumBundle\Controller\UserController"

# GET /lectures
# GET /lectures/next
# GET /lectures/{id}
lectures:
    type: rest
    resource: "N3rtrivium\KakonuntiumBundle\Controller\\LectureController"

# GET /lectures/{id}/guesses
# PUT or POST /lectures/{id}/guesses
# GET /lectures/{id}/guesses/{user-id}
# POST /lectures/{id}/guesses/admin/{pieps-id}
guesses:
    type: rest
    parent: lectures
    resource: "N3rtrivium\KakonuntiumBundle\Controller\GuessController"
