index:
    type: rest
    prefix: /
    resource: "@N3rtriviumKakonuntiumBundle/Controller/IndexController.php"


# POST /users
# GET /lectures
# GET /lectures/next
# GET /lectures/{id}
# GET /lectures/{id}/guesses
# PUT or POST /lectures/{id}/guesses
# GET /lectures/{id}/guesses/{user-id}
# POST /lectures/{id}/guesses/admin/{pieps-id}

# http://williamdurand.fr/2012/08/02/rest-apis-with-symfony2-the-right-way/
# https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/doc/index.md
# http://welcometothebundle.com/symfony2-rest-api-the-best-2013-way/