<?php

namespace N3rtrivium\KakonuntiumBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountRepository extends EntityRepository
{
}
