<?php

namespace N3rtrivium\KakonuntiumBundle\Repository;

use Doctrine\ORM\EntityRepository;
use N3rtrivium\KakonuntiumBundle\Entity\Lecture;

/**
 * CountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountRepository extends EntityRepository
{
	/**
	 * @param Lecture $lecture
	 *
	 * @return array
	 */
	public function findCountingsByLecture(Lecture $lecture)
	{

	}
}
